// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2yuEzeCYaOTPuUkSoHI272Fltu7cLbNQ',
    appId: '1:1016470733639:web:06b56a85149980b4f88262',
    messagingSenderId: '1016470733639',
    projectId: 'chat-application-631aa',
    authDomain: 'chat-application-631aa.firebaseapp.com',
    storageBucket: 'chat-application-631aa.firebasestorage.app',
    measurementId: 'G-V1C0Y8R4D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiOskaf6BPIwC-HIorofGw5gH9FmLQjA0',
    appId: '1:1016470733639:android:de6a8c1b783b95fff88262',
    messagingSenderId: '1016470733639',
    projectId: 'chat-application-631aa',
    storageBucket: 'chat-application-631aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwJN784QIC7y7kr8unYMc8HnJxxD42tnA',
    appId: '1:1016470733639:ios:809e1a1a3ed9bae7f88262',
    messagingSenderId: '1016470733639',
    projectId: 'chat-application-631aa',
    storageBucket: 'chat-application-631aa.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwJN784QIC7y7kr8unYMc8HnJxxD42tnA',
    appId: '1:1016470733639:ios:809e1a1a3ed9bae7f88262',
    messagingSenderId: '1016470733639',
    projectId: 'chat-application-631aa',
    storageBucket: 'chat-application-631aa.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2yuEzeCYaOTPuUkSoHI272Fltu7cLbNQ',
    appId: '1:1016470733639:web:d7ef9ddbeda2f748f88262',
    messagingSenderId: '1016470733639',
    projectId: 'chat-application-631aa',
    authDomain: 'chat-application-631aa.firebaseapp.com',
    storageBucket: 'chat-application-631aa.firebasestorage.app',
    measurementId: 'G-VRS5V4R2QC',
  );
}
